using AutoMapper;
using VaultGuard.Application.DTOs.Secrets;
using VaultGuard.Domain.Entities;

namespace VaultGuard.Application.Mappings;

/// <summary>
/// AutoMapper profile for VaultGuard entity-to-DTO mappings.
/// 
/// MAPPING STRATEGY:
/// - Domain entities → DTOs (for API responses)
/// - DTOs → Domain entities (for create/update operations)
/// - Explicit mappings (avoid AutoMapper conventions for security)
/// 
/// SECURITY:
/// - NEVER map plaintext values (RawValue, NewRawValue)
/// - EncryptedValue is safe to map (it's encrypted)
/// - Computed properties (IsExpired) calculated in DTO
/// </summary>
public class MappingProfile : Profile
{
    public MappingProfile()
    {
        // ====================================================================
        // SECRET MAPPINGS
        // ====================================================================

        /// <summary>
        /// Maps Secret domain entity to SecretDto (response model).
        /// 
        /// SECURITY:
        /// - EncryptedValue is mapped (safe, it's already encrypted)
        /// - IsExpired is computed property (not stored in database)
        /// - HasExpiration is computed from ExpiresAt
        /// </summary>
        CreateMap<Secret, SecretDto>()
            .ForMember(dest => dest.HasExpiration,
                opt => opt.MapFrom(src => src.ExpiresAt.HasValue))
            // IsExpired is computed in SecretDto (no mapping needed)
            .ReverseMap(); // Allow bidirectional mapping for update scenarios

        /// <summary>
        /// Maps CreateSecretDto to Secret domain entity.
        /// 
        /// SECURITY:
        /// - RawValue is NOT mapped here (handled by service layer encryption)
        /// - EncryptedValue is set by service after encrypting RawValue
        /// - UserId, CreatedAt, UpdatedAt set by service (not from DTO)
        /// </summary>
        CreateMap<CreateSecretDto, Secret>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated by service
            .ForMember(dest => dest.EncryptedValue, opt => opt.Ignore()) // Set after encryption
            .ForMember(dest => dest.UserId, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.AccessCount, opt => opt.Ignore()) // Default 0
            .ForMember(dest => dest.LastAccessedAt, opt => opt.Ignore()) // Initially null
            .ForMember(dest => dest.IsDeleted, opt => opt.Ignore()) // Default false
            .ForMember(dest => dest.DeletedAt, opt => opt.Ignore()); // Initially null

        /// <summary>
        /// Maps UpdateSecretDto to Secret domain entity (partial update).
        /// 
        /// SECURITY:
        /// - NewRawValue is NOT mapped (handled by service layer re-encryption)
        /// - Only non-null DTO properties update entity
        /// - Id is used for lookup (not updated)
        /// </summary>
        CreateMap<UpdateSecretDto, Secret>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Used for lookup only
            .ForMember(dest => dest.Title,
                opt => opt.Condition(src => !string.IsNullOrWhiteSpace(src.Title)))
            .ForMember(dest => dest.Description,
                opt => opt.Condition(src => src.Description != null))
            .ForMember(dest => dest.Category,
                opt => opt.Condition(src => src.Category != null))
            .ForMember(dest => dest.ExpiresAt,
                opt => opt.Condition(src => src.ExpiresAt.HasValue))
            .ForMember(dest => dest.EncryptedValue, opt => opt.Ignore()) // Set after re-encryption
            .ForMember(dest => dest.UserId, opt => opt.Ignore()) // Never changed
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Immutable
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.AccessCount, opt => opt.Ignore()) // Not updated here
            .ForMember(dest => dest.LastAccessedAt, opt => opt.Ignore()) // Not updated here
            .ForMember(dest => dest.IsDeleted, opt => opt.Ignore()) // Not updated here
            .ForMember(dest => dest.DeletedAt, opt => opt.Ignore()); // Not updated here

        // ====================================================================
        // AUDIT LOG MAPPINGS (If needed for admin dashboard)
        // ====================================================================

        /// <summary>
        /// Maps AuditLog domain entity to AuditLogDto (if DTO exists).
        /// Currently not used, but prepared for future admin dashboard.
        /// </summary>
        // CreateMap<AuditLog, AuditLogDto>(); // Uncomment when DTO is created

        // ====================================================================
        // USER MAPPINGS (Already defined, included for completeness)
        // ====================================================================

        /// <summary>
        /// Maps User domain entity to UserDto (response model).
        /// </summary>
        CreateMap<User, Application.DTOs.Users.UserDto>()
            .ReverseMap();

        /// <summary>
        /// Maps CreateUserDto to User domain entity.
        /// </summary>
        CreateMap<Application.DTOs.Users.CreateUserDto, User>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.PasswordHash, opt => opt.Ignore()) // Hashed by service
            .ForMember(dest => dest.SecurityStamp, opt => opt.Ignore()) // Generated by service
            .ForMember(dest => dest.RefreshToken, opt => opt.Ignore())
            .ForMember(dest => dest.RefreshTokenExpiryTime, opt => opt.Ignore())
            .ForMember(dest => dest.IsActive, opt => opt.Ignore()) // Default true
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.LastLoginAt, opt => opt.Ignore());

        /// <summary>
        /// Maps UpdateUserDto to User domain entity.
        /// </summary>
        CreateMap<Application.DTOs.Users.UpdateUserDto, User>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Email,
                opt => opt.Condition(src => !string.IsNullOrWhiteSpace(src.Email)))
            .ForMember(dest => dest.Username,
                opt => opt.Condition(src => !string.IsNullOrWhiteSpace(src.Username)))
            .ForMember(dest => dest.Role,
                opt => opt.Condition(src => !string.IsNullOrWhiteSpace(src.Role)))
            .ForMember(dest => dest.PasswordHash, opt => opt.Ignore()) // Changed separately
            .ForMember(dest => dest.SecurityStamp, opt => opt.Ignore())
            .ForMember(dest => dest.RefreshToken, opt => opt.Ignore())
            .ForMember(dest => dest.RefreshTokenExpiryTime, opt => opt.Ignore())
            .ForMember(dest => dest.IsActive, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.LastLoginAt, opt => opt.Ignore());
    }
}